services:
  postgres:
    image: postgres
    container_name: psgr
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
      - db_pg:/var/lib/postgresql/data
    networks:
      - dbnet

  server:
    build: .
    image: serv
    container_name: server
    ports:
      - "8080:8080"
    networks: 
      - dbnet
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  db_pg: